import type { Metadata } from 'next'
 import '../styles/globals.css'
 import Providers from '@/store/Providers'
 
export const metadata :Metadata  = {
  title: 'Threads',
  description: 'Generated by Next.js',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="./favicon.ico" />
      </head>

      <body suppressHydrationWarning={true}>
        <Providers>
        {children}
        </Providers>
        </body>
    </html>
  )
}

