
 import '../styles/globals.css'
 import Providers from '@/store/Providers'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Providers>
        {children}
        </Providers>
        </body>
    </html>
  )
}

